###

GET http://localhost:3000/post

###

GET http://localhost:3000/post?caption=hello

###

GET http://localhost:3000/post/6974a52a9e49711fae395562

###

GET http://localhost:3000/post/user/1234

### 

POST http://localhost:3000/post 
Content-Type: application/json

{
"caption": "hello world!!", "userId": "123456"
}

### 

DELETE http://localhost:3000/post/6974a52a9e49711fae395562

### 

PUT http://localhost:3000/post/6974a52a9e49711fae395562 
Content-Type: application/json

{
"caption": "changes!!", "userId": "123"
}

###

GET http://localhost:3000/comment

###

GET http://localhost:3000/comment?userId=123

###

GET http://localhost:3000/comment/6974a6009e49711fae39556f

### 

POST http://localhost:3000/comment 
Content-Type: application/json

{
"content": "my second comment", "userId": "123", "postId": "6974a52a9e49711fae395562"
}

###

DELETE http://localhost:3000/comment/6974a6009e49711fae39556f

### 

PUT http://localhost:3000/comment/6974a6009e49711fae39556f 
Content-Type: application/json

{
"content": "my updated comment", "userId": "123", "postId": "6974a52a9e49711fae395562"
}